"""Added relationships

Revision ID: 07c719b99173
Revises: 8b597c0dc25f
Create Date: 2023-07-25 13:06:13.244759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c719b99173'
down_revision = '8b597c0dc25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_preferences_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_preferences', ['user_preferences_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_preferences_id')

    # ### end Alembic commands ###
