"""Added zip_code to EventData model

Revision ID: 168a258cfeb3
Revises: 07c719b99173
Create Date: 2023-07-25 13:38:56.621368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168a258cfeb3'
down_revision = '07c719b99173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_data', schema=None) as batch_op:
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
